# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoskillsServer < Formula
  desc "noskills-server — persistent Claude Code sessions that survive reboots"
  homepage "https://github.com/eser/stack"
  version "4.1.60"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eser/stack/releases/download/v4.1.60/noskills_4.1.60_Darwin_x86_64.tar.gz"
      sha256 "f3945b45af4347c00673af07c7428dbbbee08276c2fa9d00c874cd649b8ecb6c"

      define_method(:install) do
        bin.install "noskills-server"
        bin.install "noskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eser/stack/releases/download/v4.1.60/noskills_4.1.60_Darwin_arm64.tar.gz"
      sha256 "caa6af05f2f8ea1d8e9cb9141ee2e1acee0df7afa09a5af0309a74189d61545d"

      define_method(:install) do
        bin.install "noskills-server"
        bin.install "noskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eser/stack/releases/download/v4.1.60/noskills_4.1.60_Linux_x86_64.tar.gz"
      sha256 "656cf5f454e516be099427dfdba179c7e0dba102ccadec319a01fe4e4f19c0c7"
      define_method(:install) do
        bin.install "noskills-server"
        bin.install "noskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eser/stack/releases/download/v4.1.60/noskills_4.1.60_Linux_arm64.tar.gz"
      sha256 "e528cdfca3cf53e1f983be88e283b87d1b461ec286d4c46464b8cc35591b259f"
      define_method(:install) do
        bin.install "noskills-server"
        bin.install "noskills"
      end
    end
  end

  def caveats
    <<~EOS
      To start noskills-server now and at login:
        brew services start noskills-server

      Or start manually:
        noskills-server start

      Get your session PIN:
        noskills-server pin

      Run a health check:
        noskills-server doctor
    EOS
  end

  service do
    run [opt_bin/"noskills-server", "start"]
    keep_alive true
    log_path var/"log/noskills-server.log"
    error_log_path var/"log/noskills-server.log"
  end
end
